---
title: "data exploration"
author: "matt maslow"
format: 
  html:
    embed-resources: true
---

# load in data

```{r}
library(tidyverse)
pbr <- read_csv("Bull Riding/BullRiders.csv")

```

# Explore the data

```{r}
head(pbr)
summary(pbr)
```





# Visualize the data

```{r}
pbr <- pbr %>%
  mutate(Age = Season - YearBorn)
```


```{r}
pbr %>%
  ggplot(aes(x = Age, y = FinalPoints)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Age vs. Ride Score",
       x = "Age",
       y = "Ride Score") 

```

```{r}
pbr %>%
  ggplot(aes(x = Height, y = FinalPoints)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Height vs. Ride Score",
       x = "Height",
       y = "Ride Score")
```

```{r}
pbr %>%
  ggplot(aes(x = Weight, y = FinalPoints)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Weight vs. Ride Score",
       x = "Weight",
       y = "Ride Score")
```


```{r}
pbr %>%
  ggplot(aes(x = Wins, y = FinalPoints)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(title = "Wins vs. Ride Score",
       x = "Wins",
       y = "Ride Score")
```


# Producing Models

```{r}
# pbr <- pbr %>% select(-Rider, -Season, -Age)
modelALL <- lm(FinalPoints ~ ., data = pbr)
summary(modelALL)
plot(modelALL)
```

*could ask questions here on model significance..... such as which predictors prove to be significant*

*could have people calculate the R^2*



```{r}
mod1 <- lm(FinalPoints ~ Height + CupPoints + Wins + Top5 + Top10, data = pbr)
summary(mod1)
print('--------------------------------------------------------------------------')
mod2 <- lm(FinalPoints ~ CupPoints + Wins + Top5, data = pbr)
summary(mod2)
```



# Lookings at the Riders Specifically

```{r}
br <- read_csv("Bull Riding/BullRiders.csv")

```

```{r}
# count the  total number of riders in data set
pbr %>%
  group_by(Rider) %>%
  summarise(n = n())
```









